/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud_interface;

/**
 *
 * @author Robin Pinto
 */
public class Crud_MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form Crud_MainWindow
     */
    public Crud_MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        label_table = new javax.swing.JLabel();
        panel_addOrDelete = new javax.swing.JPanel();
        textField_addEntry_IDReal = new javax.swing.JTextField();
        label_addEntry_title = new javax.swing.JLabel();
        label_addEntry_year = new javax.swing.JLabel();
        label_addEntry_IDReal = new javax.swing.JLabel();
        label_deleteEntry = new javax.swing.JLabel();
        button_deleteEntry = new javax.swing.JButton();
        button_addEntry = new javax.swing.JButton();
        label_addEntryMessage = new javax.swing.JLabel();
        label_addEntry = new javax.swing.JLabel();
        textField_addEntry_title = new javax.swing.JTextField();
        textField_addEntry_year = new javax.swing.JTextField();
        label_addEntry_genre = new javax.swing.JLabel();
        textField_addEntry_genre = new javax.swing.JTextField();
        textField_addEntry_resume = new javax.swing.JTextField();
        label_addEntry_resume = new javax.swing.JLabel();
        label_deleteEntryMessage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titre", "Année", "ID Réalisateur", "Genre", "Résumé"
            }
        ));
        jScrollPane1.setViewportView(table);

        label_table.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_table.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_table.setText("Table Film");

        textField_addEntry_IDReal.setText(" ");

        label_addEntry_title.setText("Titre");

        label_addEntry_year.setText("Année");

        label_addEntry_IDReal.setText("ID réalisateur");

        label_deleteEntry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_deleteEntry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_deleteEntry.setText("Supprimer une ligne");

        button_deleteEntry.setText("Supprimer");

        button_addEntry.setText("Ajouter");

        label_addEntryMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_addEntryMessage.setText(" ");

        label_addEntry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_addEntry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_addEntry.setText("Ajouter une ligne");

        textField_addEntry_title.setText(" ");

        textField_addEntry_year.setText(" ");

        label_addEntry_genre.setText("Genre");

        textField_addEntry_genre.setText(" ");

        textField_addEntry_resume.setText(" ");

        label_addEntry_resume.setText("Résumé");

        label_deleteEntryMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_deleteEntryMessage.setText(" ");

        javax.swing.GroupLayout panel_addOrDeleteLayout = new javax.swing.GroupLayout(panel_addOrDelete);
        panel_addOrDelete.setLayout(panel_addOrDeleteLayout);
        panel_addOrDeleteLayout.setHorizontalGroup(
            panel_addOrDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_deleteEntry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_deleteEntry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_addEntry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_addOrDeleteLayout.createSequentialGroup()
                .addGroup(panel_addOrDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label_addEntry_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textField_addEntry_title, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_addOrDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textField_addEntry_year)
                    .addComponent(label_addEntry_year, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_addOrDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_addEntry_IDReal, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(textField_addEntry_IDReal))
                .addGap(18, 18, 18)
                .addGroup(panel_addOrDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_addEntry_genre, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(textField_addEntry_genre))
                .addGap(18, 18, 18)
                .addGroup(panel_addOrDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_addOrDeleteLayout.createSequentialGroup()
                        .addComponent(textField_addEntry_resume, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(label_addEntry_resume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(label_addEntryMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button_addEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_deleteEntryMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_addOrDeleteLayout.setVerticalGroup(
            panel_addOrDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_addOrDeleteLayout.createSequentialGroup()
                .addComponent(label_addEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(panel_addOrDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_addEntry_title)
                    .addComponent(label_addEntry_year)
                    .addComponent(label_addEntry_IDReal)
                    .addComponent(label_addEntry_genre)
                    .addComponent(label_addEntry_resume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_addOrDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_addEntry_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_addEntry_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_addEntry_IDReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_addEntry_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_addEntry_resume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_addEntry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_addEntryMessage)
                .addGap(18, 18, 18)
                .addComponent(label_deleteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_deleteEntry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_deleteEntryMessage)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(label_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_addOrDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label_table, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_addOrDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud_MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud_MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud_MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud_MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud_MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_addEntry;
    private javax.swing.JButton button_deleteEntry;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_addEntry;
    private javax.swing.JLabel label_addEntryMessage;
    private javax.swing.JLabel label_addEntry_IDReal;
    private javax.swing.JLabel label_addEntry_genre;
    private javax.swing.JLabel label_addEntry_resume;
    private javax.swing.JLabel label_addEntry_title;
    private javax.swing.JLabel label_addEntry_year;
    private javax.swing.JLabel label_deleteEntry;
    private javax.swing.JLabel label_deleteEntryMessage;
    private javax.swing.JLabel label_table;
    private javax.swing.JPanel panel_addOrDelete;
    private javax.swing.JTable table;
    private javax.swing.JTextField textField_addEntry_IDReal;
    private javax.swing.JTextField textField_addEntry_genre;
    private javax.swing.JTextField textField_addEntry_resume;
    private javax.swing.JTextField textField_addEntry_title;
    private javax.swing.JTextField textField_addEntry_year;
    // End of variables declaration//GEN-END:variables
}
